from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.colors import HexColor

# Custom Colors
COLOR_PRIMARY = HexColor("#0D2B4E")   # Deep Navy
COLOR_SECONDARY = HexColor("#1565C0") # Bright Blue
COLOR_GRAY = HexColor("#64748B")      # Slate Gray
COLOR_BORDER = HexColor("#E2E8F0")    # Light border

def draw_header_footer(canvas, doc):
    canvas.saveState()
    # Draw top header line
    canvas.setStrokeColor(COLOR_PRIMARY)
    canvas.setLineWidth(1)
    canvas.line(40, 800, 555, 800)
    
    # Draw top header text
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(COLOR_PRIMARY)
    canvas.drawString(40, 805, "BKJ-QMS QUIZ EVALUATION SYSTEM")
    
    # Draw bottom footer line
    canvas.setStrokeColor(COLOR_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(40, 45, 555, 45)
    
    # Draw bottom footer text
    canvas.setFont("Helvetica-Oblique", 8)
    canvas.setFillColor(COLOR_GRAY)
    canvas.drawCentredString(297, 30, f"Page {doc.page} • Generated by BKJ-QMS")
    canvas.restoreState()

def build_individual_slip_pdf(result, response):
    # Setup document
    doc = SimpleDocTemplate(
        response,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=60,
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    style_title = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=COLOR_PRIMARY,
        spaceAfter=6
    )
    
    style_subtitle = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        textColor=COLOR_SECONDARY,
        spaceAfter=15
    )
    
    style_body = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.black
    )
    
    style_body_bold = ParagraphStyle(
        'BodyBoldStyle',
        parent=style_body,
        fontName='Helvetica-Bold'
    )
    
    style_th = ParagraphStyle(
        'TableHeaderStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        textColor=colors.white,
        alignment=1 # Centered
    )
    
    style_td = ParagraphStyle(
        'TableCellStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        alignment=1 # Centered
    )

    story = []
    
    # 1. Main Titles
    story.append(Paragraph("BHARAT KO JANO COMPETITION", style_title))
    story.append(Paragraph("INDIVIDUAL PERFORMANCE SLIP", style_subtitle))
    
    # 2. Candidate Information Table
    p = result.participant
    info_data = [
        [
            Paragraph("<b>Roll Number:</b>", style_body),
            Paragraph(p.roll_number, style_body_bold),
            Paragraph("<b>School Name:</b>", style_body),
            Paragraph(p.school.name, style_body_bold)
        ],
        [
            Paragraph("<b>Group & Set:</b>", style_body),
            Paragraph(f"{p.get_group_display()} ({p.get_paper_set_display()})", style_body_bold),
            Paragraph("", style_body),
            Paragraph("", style_body)
        ]
    ]
    
    info_table = Table(info_data, colWidths=[100, 155, 100, 160])
    info_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('BACKGROUND', (0,0), (-1,-1), HexColor("#F8FAFC")),
        ('BOX', (0,0), (-1,-1), 1, COLOR_BORDER),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 15))
    
    # 3. Summary Stats Table
    stats_data = [
        [
            Paragraph("<b>Questions Answered</b>", style_td),
            Paragraph("<b>Correct Answers</b>", style_td),
            Paragraph("<b>Blank / Unanswered</b>", style_td),
            Paragraph("<b>Multi-Marked</b>", style_td),
            Paragraph("<b>Percentage</b>", style_td),
            Paragraph("<b>Final Score</b>", style_td),
        ],
        [
            Paragraph(str(50 - result.unanswered_count), style_td),
            Paragraph(str(result.score), style_td),
            Paragraph(str(result.unanswered_count), style_td),
            Paragraph(str(result.multi_marked_count), style_td),
            Paragraph(f"{result.percentage}%", style_td),
            Paragraph(f"<b>{result.score} / 50</b>", style_td),
        ]
    ]
    stats_table = Table(stats_data, colWidths=[95, 90, 95, 80, 75, 80])
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_SECONDARY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOX', (0,0), (-1,-1), 1, COLOR_SECONDARY),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
    ]))
    # Overwrite header styling in stats_table
    for i in range(6):
        stats_data[0][i].style = style_th
    
    story.append(stats_table)
    story.append(Spacer(1, 20))
    
    # 4. Question Breakdown (2 columns)
    story.append(Paragraph("<b>Question-by-Question Breakdown</b>", styles['Heading3']))
    story.append(Spacer(1, 6))
    
    breakdown = result.question_breakdown
    col1_rows = []
    col2_rows = []
    
    # Headers
    header_row = [
        Paragraph("<b>Q.No</b>", style_th),
        Paragraph("<b>Marked</b>", style_th),
        Paragraph("<b>Correct</b>", style_th),
        Paragraph("<b>Status</b>", style_th)
    ]
    col1_rows.append(header_row)
    col2_rows.append(header_row)
    
    for i in range(25):
        # Col 1 (Q1 - Q25)
        item1 = breakdown[i]
        col1_rows.append([
            Paragraph(f"Q{item1['q_no']}", style_td),
            Paragraph(item1['detected'], style_td),
            Paragraph(item1['correct'], style_td),
            Paragraph(item1['status'].upper(), style_td)
        ])
        
        # Col 2 (Q26 - Q50)
        item2 = breakdown[i + 25]
        col2_rows.append([
            Paragraph(f"Q{item2['q_no']}", style_td),
            Paragraph(item2['detected'], style_td),
            Paragraph(item2['correct'], style_td),
            Paragraph(item2['status'].upper(), style_td)
        ])
        
    t1 = Table(col1_rows, colWidths=[40, 60, 60, 85])
    t2 = Table(col2_rows, colWidths=[40, 60, 60, 85])
    
    table_style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_PRIMARY),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ('TOPPADDING', (0,0), (-1,-1), 3),
        ('BOX', (0,0), (-1,-1), 1, COLOR_PRIMARY),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
    ])
    
    t1.setStyle(table_style)
    t2.setStyle(table_style)
    
    # Color rows based on status (green for correct, red for incorrect, amber for blank)
    for idx in range(1, 26):
        # Col 1 styling
        status1 = breakdown[idx - 1]['status']
        bg_color1 = HexColor("#DEF7EC") if status1 == 'correct' else (HexColor("#FDF6B2") if status1 == 'unanswered' else HexColor("#FDE8E8"))
        text_color1 = HexColor("#03543F") if status1 == 'correct' else (HexColor("#723B13") if status1 == 'unanswered' else HexColor("#9B1C1C"))
        col1_rows[idx][3].style.textColor = text_color1
        t1.setStyle(TableStyle([('BACKGROUND', (0, idx), (-1, idx), bg_color1)]))
        
        # Col 2 styling
        status2 = breakdown[idx + 24]['status']
        bg_color2 = HexColor("#DEF7EC") if status2 == 'correct' else (HexColor("#FDF6B2") if status2 == 'unanswered' else HexColor("#FDE8E8"))
        text_color2 = HexColor("#03543F") if status2 == 'correct' else (HexColor("#723B13") if status2 == 'unanswered' else HexColor("#9B1C1C"))
        col2_rows[idx][3].style.textColor = text_color2
        t2.setStyle(TableStyle([('BACKGROUND', (0, idx), (-1, idx), bg_color2)]))

    # Wrap the two tables into a parent table to show side-by-side
    side_table = Table([[t1, '', t2]], colWidths=[245, 25, 245])
    side_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(side_table)
    
    # Build PDF
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)

def build_school_results_pdf(school, results, response):
    doc = SimpleDocTemplate(
        response,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=60,
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    story = []
    
    style_title = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=COLOR_PRIMARY,
        spaceAfter=4
    )
    
    style_subtitle = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        textColor=COLOR_SECONDARY,
        spaceAfter=15
    )
    
    style_th = ParagraphStyle(
        'TH', fontName='Helvetica-Bold', fontSize=9, textColor=colors.white, alignment=1
    )
    
    style_td = ParagraphStyle(
        'TD', fontName='Helvetica', fontSize=9, alignment=1
    )
    
    style_td_left = ParagraphStyle(
        'TDLeft', fontName='Helvetica', fontSize=9, alignment=0
    )
    
    story.append(Paragraph(f"SCHOOL PERFORMANCE REPORT", style_title))
    story.append(Paragraph(f"School: {school.name}", style_subtitle))
    
    # Group results into Junior and Senior
    juniors = [r for r in results if r.participant.group == 'JUNIOR']
    seniors = [r for r in results if r.participant.group == 'SENIOR']
    
    # Calculate school stats
    total_participants = len(results)
    avg_score = sum(r.score for r in results) / total_participants if total_participants > 0 else 0
    max_score = max(r.score for r in results) if total_participants > 0 else 0
    
    stats_data = [
        [
            Paragraph("<b>Total Evaluated</b>", style_th),
            Paragraph("<b>Junior Students</b>", style_th),
            Paragraph("<b>Senior Students</b>", style_th),
            Paragraph("<b>Average Score</b>", style_th),
            Paragraph("<b>Highest Score</b>", style_th),
        ],
        [
            Paragraph(str(total_participants), style_td),
            Paragraph(str(len(juniors)), style_td),
            Paragraph(str(len(seniors)), style_td),
            Paragraph(f"{round(avg_score, 1)} / 50", style_td),
            Paragraph(f"{max_score} / 50", style_td),
        ]
    ]
    stats_table = Table(stats_data, colWidths=[100, 100, 100, 107, 108])
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_SECONDARY),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOX', (0,0), (-1,-1), 1, COLOR_SECONDARY),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
    ]))
    story.append(stats_table)
    story.append(Spacer(1, 20))
    
    def add_category_table(category_title, category_results):
        category_story = []
        category_story.append(Paragraph(f"<b>{category_title} Category</b>", styles['Heading3']))
        category_story.append(Spacer(1, 6))
        
        table_rows = [
            [
                Paragraph("<b>School Rank</b>", style_th),
                Paragraph("<b>Roll No</b>", style_th),
                Paragraph("<b>Paper Set</b>", style_th),
                Paragraph("<b>Score</b>", style_th),
                Paragraph("<b>Percentage</b>", style_th),
            ]
        ]
        
        for r in category_results:
            table_rows.append([
                Paragraph(str(r.rank), style_td),
                Paragraph(r.participant.roll_number, style_td),
                Paragraph(r.participant.get_paper_set_display()[-1], style_td),
                Paragraph(f"<b>{r.score}</b> / 50", style_td),
                Paragraph(f"{r.percentage}%", style_td),
            ])
            
        t = Table(table_rows, colWidths=[100, 120, 105, 100, 90])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), COLOR_PRIMARY),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, HexColor("#F8FAFC")]),
            ('BOX', (0,0), (-1,-1), 1, COLOR_PRIMARY),
            ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
        ]))
        category_story.append(t)
        category_story.append(Spacer(1, 20))
        return category_story
        
    if juniors:
        story.extend(add_category_table("Junior", juniors))
    if seniors:
        story.extend(add_category_table("Senior", seniors))
        
    if not results:
        story.append(Paragraph("No evaluated results found for this school.", style_td_left))
        
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)

def build_ranking_list_pdf(group, results, response):
    doc = SimpleDocTemplate(
        response,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=60,
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    story = []
    
    style_title = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        textColor=COLOR_PRIMARY,
        spaceAfter=4
    )
    
    style_subtitle = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        textColor=COLOR_SECONDARY,
        spaceAfter=15
    )
    
    style_th = ParagraphStyle(
        'TH', fontName='Helvetica-Bold', fontSize=9, textColor=colors.white, alignment=1
    )
    
    style_td = ParagraphStyle(
        'TD', fontName='Helvetica', fontSize=9, alignment=1
    )
    
    style_td_left = ParagraphStyle(
        'TDLeft', fontName='Helvetica', fontSize=9, alignment=0
    )
    
    group_name = "JUNIOR" if group.upper() == "JUNIOR" else "SENIOR"
    story.append(Paragraph(f"{group_name} CATEGORY LEADERBOARD", style_title))
    story.append(Paragraph("Official Rankings List (Dense Ranking)", style_subtitle))
    
    table_rows = [
        [
            Paragraph("<b>Rank</b>", style_th),
            Paragraph("<b>Roll No</b>", style_th),
            Paragraph("<b>School</b>", style_th),
            Paragraph("<b>Set</b>", style_th),
            Paragraph("<b>Score</b>", style_th),
            Paragraph("<b>Percentage</b>", style_th),
        ]
    ]
    
    for r in results:
        table_rows.append([
            Paragraph(f"<b>{r.rank}</b>", style_td),
            Paragraph(r.participant.roll_number, style_td),
            Paragraph(r.participant.school.name, style_td_left),
            Paragraph(r.participant.get_paper_set_display()[-1], style_td),
            Paragraph(f"<b>{r.score}</b> / 50", style_td),
            Paragraph(f"{r.percentage}%", style_td),
        ])
        
    t = Table(table_rows, colWidths=[65, 80, 210, 50, 55, 55])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), COLOR_PRIMARY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, HexColor("#F8FAFC")]),
        ('BOX', (0,0), (-1,-1), 1, COLOR_PRIMARY),
        ('INNERGRID', (0,0), (-1,-1), 0.5, COLOR_BORDER),
    ]))
    story.append(t)
    
    if not results:
        story.append(Paragraph("No evaluated results found for this category.", style_td_left))
        
    doc.build(story, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
