# Generated by Django 6.0.6 on 2026-06-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_keys', '0001_initial'),
        ('participants', '0001_initial'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrsubmission',
            name='answer_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='answer_keys.answerkey'),
        ),
        migrations.AlterField(
            model_name='omrsubmission',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='omr_submission', to='participants.participant'),
        ),
    ]
